// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class branche
{
    public int branch_ID { get; set; }

    public string name { get; set; }

    public string location { get; set; }

    public virtual ICollection<department> depts { get; set; } = new List<department>();
}