// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class Dept_ins_SelectResult
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public string Dept_Name { get; set; }
        public DateTime? hire_date { get; set; }
    }
}
