// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class exam
{
    public int exam_ID { get; set; }

    public TimeSpan? time { get; set; }

    public DateTime? date { get; set; }

    public int? duration { get; set; }

    public int? course_ID { get; set; }

    public virtual course course { get; set; }

    public virtual ICollection<st_answer> st_answers { get; set; } = new List<st_answer>();

    public virtual ICollection<st_exam> st_exams { get; set; } = new List<st_exam>();

    public virtual ICollection<question> quesations { get; set; } = new List<question>();
}