// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class GetCoursesAndStudentsByInstructorResult
    {
        public string course_name { get; set; }
        public int? num_students { get; set; }
    }
}
