// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class GetExamQuestionsAndChoicesResult
    {
        public int exam_ID { get; set; }
        public int quesation_ID { get; set; }
        public string question_text { get; set; }
        public string opt1 { get; set; }
        public string opt2 { get; set; }
        public string opt3 { get; set; }
        public string opt4 { get; set; }
    }
}
