// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class GetStudentsByDepartmentResult
    {
        public int st_ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public int? age { get; set; }
        public string address { get; set; }
        public int? dept_ID { get; set; }
    }
}
