// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class ins_course_dept
{
    public int ins_ID { get; set; }

    public int dept_ID { get; set; }

    public int course_ID { get; set; }

    public virtual course course { get; set; }

    public virtual department dept { get; set; }

    public virtual instructor ins { get; set; }
}