// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class INS_selectResult
    {
        public int ins_ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public decimal salary { get; set; }
        public string Degree { get; set; }
        public DateTime? hire_date { get; set; }
    }
}
