// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class Ins_Dept_Crs_SelectResult
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public string Dept_Name { get; set; }
        public string Course_name { get; set; }
        public int? duration { get; set; }
    }
}
