// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class instructor
{
    public int ins_ID { get; set; }

    public string fname { get; set; }

    public string lname { get; set; }

    public decimal salary { get; set; }

    public string Degree { get; set; }

    public DateTime? hire_date { get; set; }

    public virtual ICollection<department> departments { get; set; } = new List<department>();

    public virtual ICollection<ins_course_dept> ins_course_depts { get; set; } = new List<ins_course_dept>();

    public virtual ICollection<department> depts { get; set; } = new List<department>();
}