// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DB_Sytem.Models;

namespace DB_Sytem.Models
{
    public partial class ITIDBContext
    {

        [DbFunction("ifcanDeleteCourse", "dbo")]
        public static int? ifcanDeleteCourse(int? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
