// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class question_option
{
    public int question_ID { get; set; }

    public string opt1 { get; set; }

    public string opt2 { get; set; }

    public string opt3 { get; set; }

    public string opt4 { get; set; }

    public virtual question question { get; set; }
}