// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class select_AllQuestionsResult
    {
        public int question_ID { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string correct_ans { get; set; }
        public int? grade { get; set; }
        public int? course_ID { get; set; }
    }
}
