// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class Select_BrancheResult
    {
        public int branch_ID { get; set; }
        public string name { get; set; }
        public string location { get; set; }
    }
}
