// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class selectStudentCourseResult
    {
        public int st_ID { get; set; }
        public string FullName { get; set; }
        public int course_ID { get; set; }
        public string Course_Name { get; set; }
    }
}
