// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class select_st_examResult
    {
        public string FullName { get; set; }
        public int exam_ID { get; set; }
        public int? total_degree { get; set; }
    }
}
