// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class select_examResult
    {
        public TimeSpan? time { get; set; }
        public DateTime? date { get; set; }
        public int? duration { get; set; }
        public string courseName { get; set; }
    }
}
