// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_Sytem.Models
{
    public partial class select_ExamQuestionsResult
    {
        public int exam_ID { get; set; }
        public int quesation_ID { get; set; }
    }
}
