// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class st_answer
{
    public int exam_ID { get; set; }

    public int st_ID { get; set; }

    public int question_ID { get; set; }

    public string answer { get; set; }

    public int? grade { get; set; }

    public virtual exam exam { get; set; }

    public virtual question question { get; set; }

    public virtual student st { get; set; }
}