// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Sytem.Models;

public partial class st_exam
{
    public int st_ID { get; set; }

    public int exam_ID { get; set; }

    public int? total_degree { get; set; }

    public virtual exam exam { get; set; }

    public virtual student st { get; set; }
}